import type { NextAuthOptions } from "next-auth"
import GoogleProvider from "next-auth/providers/google"
import CredentialsProvider from "next-auth/providers/credentials"

import { displayNameFromEmail, generatePersona } from "@/lib/persona"
import { verifyMagicLinkToken } from "@/lib/auth/magic-link"
import { isAdminEmail } from "@/lib/admin-allowlist"

const hasGoogle =
  !!process.env.GOOGLE_CLIENT_ID && !!process.env.GOOGLE_CLIENT_SECRET

const useSecureCookies =
  (process.env.NEXTAUTH_URL ?? "").startsWith("https://") ||
  process.env.NODE_ENV === "production"

/**
 * NextAuth config for the sof.ai gateway.
 *
 * `sof.ai` and `*.thevrschool.org` are different top-level domains, so a
 * cookie can't be shared across both. Instead, we share the same
 * NEXTAUTH_SECRET + the same Postgres user records — when a Pioneer signs
 * in on either side, the underlying identity (email, name, image) maps
 * to the same row, and journals/applications are unified. The first
 * sign-in click on the *other* TLD costs one extra round-trip; everything
 * else is invisible to the visitor.
 *
 * JWT-only (no DB adapter) for now. Branch 3 layers a thin upsert into
 * the shared user table on first successful sign-in so a Pioneer signing
 * in here for the first time becomes a real user record everywhere.
 */
export const authOptions: NextAuthOptions = {
  session: { strategy: "jwt" },
  secret: process.env.NEXTAUTH_SECRET ?? "dev-insecure-secret-change-me",
  pages: {
    signIn: "/signin",
  },
  cookies: useSecureCookies
    ? {
        sessionToken: {
          name: "__Secure-next-auth.session-token",
          options: {
            httpOnly: true,
            sameSite: "lax",
            path: "/",
            secure: true,
          },
        },
      }
    : {},
  providers: [
    ...(hasGoogle
      ? [
          GoogleProvider({
            clientId: process.env.GOOGLE_CLIENT_ID!,
            clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
          }),
        ]
      : []),
    // One-click guest entry. Zero fields required — `/signin` calls
    // signIn("guest", { handle, displayName }) with values generated by
    // lib/persona, so onboarding is effectively passwordless and <1s.
    CredentialsProvider({
      id: "guest",
      name: "Continue as guest",
      credentials: {
        handle: { label: "Handle", type: "text" },
        displayName: { label: "Display name", type: "text" },
      },
      async authorize(credentials) {
        const generated = generatePersona()
        const handle = credentials?.handle?.trim() || generated.handle
        const displayName =
          credentials?.displayName?.trim() || generated.displayName
        // Mint a UUID so two guests sharing the same generated handle
        // (the persona pool is small) don't collide on the account key.
        // The handle stays for display only.
        const uniqueId = crypto.randomUUID()
        return {
          id: `guest:${uniqueId}`,
          email: `${handle}@guest.sof.ai`,
          name: displayName,
          image: null,
        }
      },
    }),
    // Magic-link via the AI School FastAPI. /signin/magic lands here with
    // a token in the URL and exchanges it for the verified email. The
    // token is consumed atomically server-side (single-use, expiring).
    CredentialsProvider({
      id: "magic-link",
      name: "Email magic link",
      credentials: {
        token: { label: "Token", type: "text" },
      },
      async authorize(credentials) {
        const token = credentials?.token?.trim()
        if (!token) return null
        try {
          const email = await verifyMagicLinkToken(token)
          if (!email || !email.includes("@")) return null
          const name = displayNameFromEmail(email)
          return { id: `email:${email}`, email, name, image: null }
        } catch {
          return null
        }
      },
    }),
  ],
  callbacks: {
    async jwt({ token, user }) {
      if (user) {
        token.id = user.id
        token.email = user.email
        token.name = user.name
        token.picture = user.image
      }
      return token
    },
    async session({ session, token }) {
      if (session.user) {
        session.user.email = (token.email as string | undefined) ?? null
        session.user.name = (token.name as string | undefined) ?? null
        session.user.image = (token.picture as string | undefined) ?? null
        // Surface admin status to the client so the navbar can render
        // the Steward link without exposing the allowlist contents.
        // Server routes still re-check against the allowlist before
        // doing anything mutative — this flag is for UI affordance only.
        session.user.isAdmin = isAdminEmail(session.user.email)
      }
      return session
    },
  },
}
