
export type UcSection = "A" | "B" | "C" | "D" | "E" | "F" | "G"
export type CourseLength = "1 Year" | "1/2 Year"

export interface Course {
  title: string
  slug: string
  section: UcSection
  discipline: string
  length: CourseLength
  ucHonors: boolean
}

export const SECTION_META: Record<UcSection, { label: string; color: string }> = {
  A: { label: "History & Social Science",    color: "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300" },
  B: { label: "English",                     color: "bg-sky-100 text-sky-800 dark:bg-sky-950 dark:text-sky-300" },
  C: { label: "Mathematics",                 color: "bg-violet-100 text-violet-800 dark:bg-violet-950 dark:text-violet-300" },
  D: { label: "Science",                     color: "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300" },
  E: { label: "Language Other than English", color: "bg-rose-100 text-rose-800 dark:bg-rose-950 dark:text-rose-300" },
  F: { label: "Visual & Performing Arts",    color: "bg-fuchsia-100 text-fuchsia-800 dark:bg-fuchsia-950 dark:text-fuchsia-300" },
  G: { label: "College-Preparatory Elective", color: "bg-stone-100 text-stone-700 dark:bg-stone-800 dark:text-stone-300" },
}

function s(title: string, section: UcSection, discipline: string, length: CourseLength, ucHonors = false): Course {
  return {
    title,
    slug: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
    section,
    discipline,
    length,
    ucHonors,
  }
}

export const COURSES: Course[] = [
  // ── A: History & Social Science ──────────────────────────
  s("American Culture and Society",                     "A","U.S. History",                        "1 Year",   true),
  s("AP European History",                              "A","World History",                        "1 Year",   true),
  s("AP Government and Politics Comparative",           "A","Civics / American Government",         "1/2 Year", true),
  s("AP Human Geography",                               "A","World History",                        "1 Year",   true),
  s("AP United States History",                         "A","U.S. History",                        "1 Year",   true),
  s("AP World History",                                 "A","World History",                        "1 Year",   true),
  s("Critical Media Literacy: Analyzing Primary Sources","A","World History",                        "1/2 Year", false),
  s("Pre-AP World History & Geography",                 "A","World History",                        "1 Year",   false),

  // ── B: English ───────────────────────────────────────────
  s("Advanced Applied Medical English",                 "B","English",                             "1 Year",   true),
  s("AP English Literature and Composition",            "B","English",                             "1 Year",   true),
  s("AP Seminar",                                       "B","English",                             "1 Year",   true),
  s("English 9",                                        "B","English",                             "1 Year",   false),
  s("Pre-AP English 1",                                 "B","English",                             "1 Year",   false),
  s("Pre-AP English 2",                                 "B","English",                             "1 Year",   false),

  // ── C: Mathematics ───────────────────────────────────────
  s("AP Calculus AB",                                   "C","Calculus",                            "1 Year",   true),
  s("AP Calculus BC",                                   "C","Calculus",                            "1 Year",   true),
  s("AP Precalculus",                                   "C","Pre-Calculus",                        "1 Year",   true),
  s("Integrated Geometry and Algebra",                  "C","Mathematics II",                      "1 Year",   false),
  s("Introductory Calculus",                            "C","Calculus",                            "1 Year",   false),
  s("Pre-AP Algebra 2",                                 "C","Algebra II",                          "1 Year",   false),
  s("Pre-AP Algebra I",                                 "C","Algebra I",                           "1 Year",   false),
  s("Pre-AP Geometry and Statistics",                   "C","Geometry",                            "1 Year",   false),

  // ── D: Science ───────────────────────────────────────────
  s("AP Chemistry",                                     "D","Chemistry",                           "1 Year",   true),
  s("AP Environmental Science",                         "D","Interdisciplinary Sciences",          "1 Year",   true),
  s("AP Physics 1",                                     "D","Physics",                             "1 Year",   true),
  s("AP Physics 2",                                     "D","Physics",                             "1 Year",   true),
  s("AP Physics C: Electricity and Magnetism",          "D","Physics",                             "1 Year",   true),
  s("AP Physics C: Mechanics",                          "D","Physics",                             "1 Year",   true),
  s("Clinical Anatomy & Physiology",                    "D","Biology / Life Sciences",             "1 Year",   false),
  s("Conceptual Physics",                               "D","Integrated Science",                  "1 Year",   false),
  s("Game Design in Unity with Virtual Reality",        "D","Engineering",                         "1 Year",   true),
  s("Intro to Cybersecurity",                           "D","Computer Science",                    "1 Year",   false),
  s("Pre-AP Biology",                                   "D","Biology / Life Sciences",             "1 Year",   false),
  s("Pre-AP Chemistry",                                 "D","Chemistry",                           "1 Year",   false),

  // ── E: Language Other than English ───────────────────────
  s("AP Chinese Language and Culture",                  "E","LOTE Level 4+",                       "1 Year",   true),
  s("AP French Language and Culture",                   "E","LOTE Level 4+",                       "1 Year",   true),
  s("AP German Language and Culture",                   "E","LOTE Level 4+",                       "1 Year",   true),
  s("AP Italian Language and Culture",                  "E","LOTE Level 4+",                       "1 Year",   true),
  s("AP Japanese Language and Culture",                 "E","LOTE Level 4+",                       "1 Year",   true),
  s("AP Latin",                                         "E","LOTE Level 4+",                       "1 Year",   true),
  s("AP Spanish Language and Culture",                  "E","LOTE Level 4+",                       "1 Year",   true),
  s("AP Spanish Literature and Culture",                "E","LOTE Level 4+",                       "1 Year",   true),

  // ── F: Visual & Performing Arts ──────────────────────────
  s("Advanced Studio Art Honors",                       "F","Visual Arts",                         "1 Year",   true),
  s("AI-Inspired Tactile Art",                          "F","Visual Arts",                         "1 Year",   false),
  s("AP 2D Art and Design",                             "F","Visual Arts",                         "1 Year",   true),
  s("AP 3D Art and Design",                             "F","Visual Arts",                         "1 Year",   true),
  s("AP Art History",                                   "F","Visual Arts",                         "1 Year",   true),
  s("AP Drawing",                                       "F","Visual Arts",                         "1 Year",   true),
  s("Artificial Intelligence Design and Development",   "F","Interdisciplinary Arts",              "1 Year",   false),
  s("Pre-AP Arts - Dance",                              "F","Dance",                               "1 Year",   false),
  s("Pre-AP Arts - Music",                              "F","Music",                               "1 Year",   false),
  s("Pre-AP Arts - Theatre",                            "F","Theater",                             "1 Year",   false),
  s("Pre-AP Arts - Visual Arts",                        "F","Visual Arts",                         "1 Year",   false),

  // ── G: College-Preparatory Elective ──────────────────────
  s("Advanced Computer Science with AI Agents",           "G","Interdisciplinary",                "1 Year",   true),
  s("Agile Project Management Principles and Practices - Semester 1","G","Interdisciplinary","1/2 Year",false),
  s("Agile Project Management Principles and Practices - Semester 2","G","Interdisciplinary","1/2 Year",false),
  s("AI & Media Literacy",                                "G","Interdisciplinary",                "1 Year",   false),
  s("AI and Machine Learning",                            "G","Interdisciplinary",                "1 Year",   false),
  s("AI in Business: A Professional Internship",          "G","Interdisciplinary",                "1 Year",   false),
  s("AI in the Economy: The Business and Financial Impacts of Artificial Intelligence","G","Interdisciplinary","1/2 Year",false),
  s("AI Literacy",                                        "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("American Education and Integration",                 "G","History / Social Science",         "1/2 Year", false),
  s("American Stories: The Great Depression, Civil Rights, and Social Change","G","History / Social Science","1/2 Year",false),
  s("Anatomy & Physiology Foundations",                   "G","Interdisciplinary",                "1 Year",   false),
  s("Anatomy and Physiology - Body Systems - Semester 2", "G","Science - Biology / Life Sciences","1/2 Year", false),
  s("Anatomy and Physiology - Foundations - Semester 1",  "G","Science - Biology / Life Sciences","1/2 Year", false),
  s("AP Macroeconomics",                                  "G","History / Social Science",         "1/2 Year", true),
  s("AP Microeconomics",                                  "G","History / Social Science",         "1/2 Year", true),
  s("AP Psychology",                                      "G","History / Social Science",         "1 Year",   true),
  s("AP Research",                                        "G","Interdisciplinary",                "1 Year",   true),
  s("Art, Consciousness, and AI",                         "G","Interdisciplinary",                "1/2 Year", false),
  s("Artificial Intelligence & Machine Learning Honors",  "G","Mathematics - Computer Science",   "1/2 Year", true),
  s("Artificial Intelligence and Emerging Technologies - Semester 1","G","Interdisciplinary","1/2 Year",false),
  s("Artificial Intelligence and Emerging Technologies - Semester 2","G","Interdisciplinary","1/2 Year",false),
  s("Artificial Intelligence and Machine Learning Fundamentals - Semester 1","G","Mathematics - Computer Science","1/2 Year",false),
  s("Artificial Intelligence and Machine Learning Fundamentals - Semester 2","G","Mathematics - Computer Science","1/2 Year",false),
  s("Artificial Intelligence and Social Justice",         "G","Interdisciplinary",                "1/2 Year", false),
  s("Augmented and Virtual Reality Applications",         "G","Interdisciplinary",                "1/2 Year", false),
  s("Backyard Homesteading and Self-Sufficiency - Semester 2","G","Interdisciplinary",            "1/2 Year", false),
  s("Backyard Homesteading and Self-Sufficiency - Semester 3","G","Interdisciplinary",            "1/2 Year", false),
  s("Backyard Homesteading and Self-Sufficiency - Semester 4","G","Interdisciplinary",            "1/2 Year", false),
  s("Backyard Homesteading and Self-Sufficiency - Semester 5","G","Interdisciplinary",            "1/2 Year", false),
  s("Ballet Fundamentals - Semester 1",                   "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Ballet Fundamentals - Semester 2",                   "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Beginning Programming",                              "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Beginning Programming with Python",                  "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Blockchain and Decentralized Systems - Semester 1",  "G","Interdisciplinary",                "1/2 Year", false),
  s("Blockchain and Decentralized Systems - Semester 2",  "G","Interdisciplinary",                "1/2 Year", false),
  s("Bollywood Dance and Culture - Semester 1",           "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Bollywood Dance and Culture - Semester 2",           "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Budget Travel and Global Exploration - Semester 2",  "G","Interdisciplinary",                "1/2 Year", false),
  s("Building and Recording in a Home Studio - Semester 1","G","Visual & Performing Arts",        "1/2 Year", false),
  s("Building and Recording in a Home Studio - Semester 2","G","Visual & Performing Arts",        "1/2 Year", false),
  s("Building Information Modeling (BIM) - Semester 1",  "G","Interdisciplinary",                "1/2 Year", false),
  s("Building Information Modeling (BIM) - Semester 2",  "G","Interdisciplinary",                "1/2 Year", false),
  s("C# Programming Fundamentals",                        "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Career Development and Readiness - Semester 2",      "G","Interdisciplinary",                "1/2 Year", false),
  s("Career Development and Readiness - Semester 3",      "G","Interdisciplinary",                "1/2 Year", false),
  s("Career Development and Readiness - Semester 4",      "G","Interdisciplinary",                "1/2 Year", false),
  s("Career Development and Readiness - Semester 5",      "G","Interdisciplinary",                "1/2 Year", false),
  s("Career Development and Readiness - Semester 6",      "G","Interdisciplinary",                "1/2 Year", false),
  s("ChatGPT Foundations - Semester 1",                   "G","Interdisciplinary",                "1/2 Year", false),
  s("ChatGPT Foundations - Semester 2",                   "G","Interdisciplinary",                "1/2 Year", false),
  s("Civil War Memoirs and Reconstruction",               "G","History / Social Science",         "1/2 Year", false),
  s("Clinical Anatomy",                                   "G","Interdisciplinary",                "1/2 Year", false),
  s("Clinical Nutrition: Principles and Practice",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Coding - Java 2",                                    "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Coding Java 1",                                      "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Coding with Python for Beginners",                   "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Cold War and Global Politics",                       "G","History / Social Science",         "1/2 Year", false),
  s("Computer Networking and Security - Semester 1",      "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Computer Networking and Security - Semester 2",      "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Corporate Finance and Business Strategy - Semester 1","G","Interdisciplinary",               "1/2 Year", false),
  s("Corporate Finance and Business Strategy - Semester 2","G","Interdisciplinary",               "1/2 Year", false),
  s("Creating YouTube Videos - Semester 2",               "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Criminal Justice in Action - Semester 1",            "G","Interdisciplinary",                "1/2 Year", false),
  s("Criminal Justice in Action - Semester 2",            "G","Interdisciplinary",                "1/2 Year", false),
  s("Cultural Reflection: Technology, Invention, Everyday Life","G","History / Social Science",   "1/2 Year", false),
  s("Cybersecurity and Information Protection - Semester 1","G","Mathematics - Computer Science", "1/2 Year", false),
  s("Cybersecurity and Information Protection - Semester 2","G","Mathematics - Computer Science", "1/2 Year", false),
  s("Cybersecurity Foundations - Semester 1",             "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Cybersecurity Foundations - Semester 2",             "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Cybersecurity Foundations - Semester 3",             "G","Interdisciplinary",                "1/2 Year", false),
  s("Data Analysis with Excel - Semester 1",              "G","Interdisciplinary",                "1/2 Year", false),
  s("Data Analysis with Excel - Semester 2",              "G","Interdisciplinary",                "1/2 Year", false),
  s("Data Science (Python)",                              "G","Mathematics",                      "1 Year",   false),
  s("Deep Learning Foundations",                          "G","Interdisciplinary",                "1 Year",   false),
  s("Design Thinking and Innovation - Semester 1",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Design Thinking and Innovation - Semester 2",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Design Thinking and Innovation I",                   "G","Interdisciplinary",                "1 Year",   false),
  s("DevOps and Cloud Practices - Semester 1",            "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("DevOps and Cloud Practices - Semester 2",            "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Digital Fabrication: From Design to Prototype",      "G","Interdisciplinary",                "1 Year",   false),
  s("Digital Marketing Fundamentals - Semester 1",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Digital Marketing Fundamentals - Semester 2",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Digital Nomads and Remote Work - Semester 1",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Drone Piloting Foundations - Semester 1",            "G","Interdisciplinary",                "1/2 Year", false),
  s("Drone Piloting Foundations - Semester 2",            "G","Interdisciplinary",                "1/2 Year", false),
  s("Drone Technology and Applications - Semester 1",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Drone Technology and Applications - Semester 2",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Effective Business Communication Foundations - Semester 1","G","Interdisciplinary",          "1/2 Year", false),
  s("Effective Business Communication Foundations - Semester 2","G","Interdisciplinary",          "1/2 Year", false),
  s("EMT Foundations and Exam Preparation - Semester 1",  "G","Interdisciplinary",                "1/2 Year", false),
  s("EMT Foundations and Exam Preparation - Semester 2",  "G","Interdisciplinary",                "1/2 Year", false),
  s("EngageXR: Virtual Reality and Digital Spaces",       "G","Interdisciplinary",                "1/2 Year", false),
  s("Entrepreneurship and Innovation - Semester 1",       "G","Interdisciplinary",                "1/2 Year", false),
  s("Entrepreneurship and Innovation - Semester 2",       "G","Interdisciplinary",                "1/2 Year", false),
  s("Entrepreneurship and Innovation in American Life",   "G","History / Social Science",         "1/2 Year", false),
  s("Environmental Science and Sustainability - Semester 1","G","Interdisciplinary",              "1/2 Year", false),
  s("Environmental Science and Sustainability - Semester 2","G","Interdisciplinary",              "1/2 Year", false),
  s("Ethics and Artificial Intelligence",                 "G","Interdisciplinary",                "1/2 Year", true),
  s("Exploring Ethics in Clinical Practice",              "G","Interdisciplinary",                "1/2 Year", false),
  s("Family Histories and Personal Narratives",           "G","History / Social Science",         "1/2 Year", false),
  s("Film as Literature I",                               "G","English",                          "1/2 Year", false),
  s("Filmmaking and Digital Media - Semester 1",          "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Filmmaking and Digital Media - Semester 2",          "G","Interdisciplinary",                "1/2 Year", false),
  s("Financial Accounting - Semester 1",                  "G","Interdisciplinary",                "1/2 Year", false),
  s("Financial Accounting - Semester 2",                  "G","Interdisciplinary",                "1/2 Year", false),
  s("Financial Security and Planning - Semester 1",       "G","Interdisciplinary",                "1/2 Year", false),
  s("Financial Security and Planning - Semester 2",       "G","Interdisciplinary",                "1/2 Year", false),
  s("First-Year Teaching - Semester 1",                   "G","Interdisciplinary",                "1/2 Year", false),
  s("First-Year Teaching - Semester 2",                   "G","Interdisciplinary",                "1/2 Year", false),
  s("Food Truck Management and Entrepreneurship - Semester 1","G","Interdisciplinary",            "1/2 Year", false),
  s("Food Truck Management and Entrepreneurship - Semester 2","G","Interdisciplinary",            "1/2 Year", false),
  s("Forensic Science and Criminal Investigation - Semester 1","G","Interdisciplinary",           "1/2 Year", false),
  s("Forensic Science and Criminal Investigation - Semester 2","G","Interdisciplinary",           "1/2 Year", false),
  s("Foundations and Career Paths in Culinary Arts - Semester 1","G","Interdisciplinary",         "1/2 Year", false),
  s("Foundations and Career Paths in Culinary Arts - Semester 2","G","Interdisciplinary",         "1/2 Year", false),
  s("Foundations of Beef Cattle Management - Semester 1", "G","Interdisciplinary",                "1/2 Year", false),
  s("Foundations of Beef Cattle Management - Semester 2", "G","Interdisciplinary",                "1/2 Year", false),
  s("Foundations of Healthcare IT - Semester 1",          "G","Interdisciplinary",                "1/2 Year", false),
  s("Foundations of Healthcare IT - Semester 2",          "G","Interdisciplinary",                "1/2 Year", false),
  s("Foundations of Playwriting - Semester 1",            "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Foundations of Playwriting - Semester 2",            "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Functional Programming Foundations",                 "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Fundamentals of Medical Ethics",                     "G","Interdisciplinary",                "1/2 Year", false),
  s("Fundamentals of Nutrition",                          "G","Interdisciplinary",                "1/2 Year", false),
  s("Generative AI - Foundations and Applications",       "G","Mathematics",                      "1 Year",   false),
  s("GIS Foundations and Applications",                   "G","Interdisciplinary",                "1 Year",   false),
  s("GIS Fundamentals with ArcGIS",                       "G","Interdisciplinary",                "1/2 Year", false),
  s("GIS Image Processing and Remote Sensing Analysis",   "G","Interdisciplinary",                "1 Year",   false),
  s("Global Logistics Fundamentals - Semester 1",         "G","Interdisciplinary",                "1/2 Year", false),
  s("Global Logistics Fundamentals - Semester 2",         "G","Interdisciplinary",                "1/2 Year", false),
  s("Google Applications",                                "G","Interdisciplinary",                "1/2 Year", false),
  s("Graphic Design and Visual Communication - Semester 1","G","Visual & Performing Arts",        "1/2 Year", false),
  s("Graphic Design and Visual Communication - Semester 2","G","Visual & Performing Arts",        "1/2 Year", false),
  s("Green Building and Remodeling - Semester 1",         "G","Science - Biology / Life Sciences","1/2 Year", false),
  s("Green Building and Remodeling - Semester 2",         "G","Science - Biology / Life Sciences","1/2 Year", false),
  s("Healthcare and Medical Advancements",                "G","History / Social Science",         "1/2 Year", false),
  s("Healthcare in Modern America",                       "G","Interdisciplinary",                "1/2 Year", false),
  s("Hobby Farming and Sustainable Agriculture - Semester 1","G","Science - Biology / Life Sciences","1/2 Year",false),
  s("Hobby Farming and Sustainable Agriculture - Semester 2","G","Science - Biology / Life Sciences","1/2 Year",false),
  s("Home Recording and Audio Production - Semester 1",   "G","Interdisciplinary",                "1/2 Year", false),
  s("Home Recording and Audio Production - Semester 2",   "G","Visual & Performing Arts",         "1/2 Year", false),
  s("HTML, CSS & JavaScript Foundations",                 "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Instructional Design and Learning Technologies - Semester 1","G","Interdisciplinary",        "1/2 Year", false),
  s("Instructional Design and Learning Technologies - Semester 2","G","Interdisciplinary",        "1/2 Year", false),
  s("Intro to Computer Science",                          "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Intro to Computer Science Education - AI",           "G","Interdisciplinary",                "1/2 Year", false),
  s("Intro to Kinesiology - CTE",                         "G","Interdisciplinary",                "1 Year",   false),
  s("Introduction to Algorithms",                         "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Introduction to Architecture - Semester 1",          "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Introduction to Architecture - Semester 2",          "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Introduction to Arduino Programming and Hardware - Semester 1","G","Interdisciplinary",      "1/2 Year", false),
  s("Introduction to Arduino Programming and Hardware - Semester 2","G","Interdisciplinary",      "1/2 Year", false),
  s("Introduction to Artificial Intelligence Honors: Informatics","G","Mathematics - Computer Science","1/2 Year",true),
  s("Introduction to Coding",                             "G","Interdisciplinary",                "1 Year",   false),
  s("Introduction to Coding - Semester 1",                "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Introduction to Coding - Semester 2",                "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Introduction to Coding - Semester 3",                "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Introduction to Criminal Justice Careers - Semester 1","G","Interdisciplinary",              "1/2 Year", false),
  s("Introduction to Criminal Justice Careers - Semester 2","G","Interdisciplinary",              "1/2 Year", false),
  s("Introduction to Data Science and Machine Learning (AI)","G","Mathematics - Computer Science","1 Year",   false),
  s("Introduction to Kinesiology and Human Movement",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Introduction to Law and Legal Systems - Semester 1", "G","History / Social Science",         "1/2 Year", false),
  s("Introduction to Law and Legal Systems - Semester 2", "G","History / Social Science",         "1/2 Year", false),
  s("Introduction to Programming with C++",               "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Introduction to Python Programming - Semester 1",    "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Introduction to Python Programming - Semester 2",    "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Introduction to Robotics and Programmable Systems - Semester 1","G","Mathematics - Computer Science","1/2 Year",false),
  s("Introduction to Robotics and Programmable Systems - Semester 2","G","Mathematics - Computer Science","1/2 Year",false),
  s("Introduction to U.S. Constitutional Law - Semester 1","G","History / Social Science",        "1/2 Year", false),
  s("Introduction to U.S. Constitutional Law - Semester 2","G","History / Social Science",        "1/2 Year", false),
  s("Investing and Wealth Management - Semester 2",       "G","Interdisciplinary",                "1/2 Year", false),
  s("Investment Banking Fundamentals - Semester 1",       "G","Interdisciplinary",                "1/2 Year", false),
  s("Investment Banking Fundamentals - Semester 2",       "G","Interdisciplinary",                "1/2 Year", false),
  s("IoS App Development with Swift",                     "G","Interdisciplinary",                "1 Year",   false),
  s("Java Programming for Beginners",                     "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Java Programming Foundations",                       "G","Mathematics - Computer Science",   "1 Year",   false),
  s("JavaScript Programming",                             "G","Mathematics - Computer Science",   "1 Year",   false),
  s("JFK - An American Hero",                             "G","History / Social Science",         "1/2 Year", false),
  s("Junior MBA I: Foundations of Business & Management", "G","Interdisciplinary",                "1/2 Year", false),
  s("Law Enforcement and Justice",                        "G","History / Social Science",         "1/2 Year", false),
  s("Leadership Through Personal Narrative I: Psychology of Resilience","G","Interdisciplinary",  "1/2 Year", false),
  s("Leadership Through Personal Narrative II: Women's Economic Empowerment and Entrepreneurship","G","Interdisciplinary","1/2 Year",false),
  s("Leadership Through Personal Narrative III: Social Systems and Policy Analysis","G","Interdisciplinary","1/2 Year",false),
  s("Leadership Through Personal Narrative IV: Military Studies and Crisis Leadership","G","Interdisciplinary","1/2 Year",false),
  s("Leadership Through Personal Narrative V: Health, Wellness, and Performance Psychology","G","Interdisciplinary","1/2 Year",false),
  s("Lean Six Sigma and Process Improvement - Semester 1","G","Interdisciplinary",                "1/2 Year", false),
  s("Lean Six Sigma and Process Improvement - Semester 2","G","Interdisciplinary",                "1/2 Year", false),
  s("Machine Learning Foundations - Semester 1",          "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Machine Learning Foundations - Semester 2",          "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Managing Money and Financial Planning - Semester 1", "G","Interdisciplinary",                "1/2 Year", false),
  s("Managing Money and Financial Planning - Semester 2", "G","Interdisciplinary",                "1/2 Year", false),
  s("Managing Money and Financial Planning - Semester 3", "G","Interdisciplinary",                "1/2 Year", false),
  s("Mastering Blogging: From Idea to Income",            "G","Interdisciplinary",                "1 Year",   false),
  s("Media and Memory - Storytelling through Video",      "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Medical Billing and Coding",                         "G","Interdisciplinary",                "1/2 Year", false),
  s("Medical Dosage Calculations",                        "G","Interdisciplinary",                "1/2 Year", false),
  s("Medical Terminology",                                "G","Interdisciplinary",                "1/2 Year", false),
  s("Memoirs of the 20th Century",                        "G","History / Social Science",         "1/2 Year", false),
  s("Middle East Conflicts & The War on Terror",          "G","History / Social Science",         "1/2 Year", false),
  s("Mobile App Development - Flutter",                   "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Music Composition and Creativity - Semester 1",      "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Music Composition and Creativity - Semester 2",      "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Music Theory and Composition - Semester 1",          "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Music Theory and Composition - Semester 2",          "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Musical Theatre and Performance - Semester 1",       "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Musical Theatre and Performance - Semester 2",       "G","Interdisciplinary",                "1/2 Year", false),
  s("Narrative Writing from History: Telling Our Stories","G","English",                          "1/2 Year", false),
  s("NCLEX-RN Exam Preparation - Semester 1",             "G","Interdisciplinary",                "1/2 Year", false),
  s("NCLEX-RN Exam Preparation - Semester 2",             "G","Interdisciplinary",                "1/2 Year", false),
  s("Networking Foundations - Semester 1",                "G","Interdisciplinary",                "1/2 Year", false),
  s("Networking Foundations - Semester 2",                "G","Interdisciplinary",                "1/2 Year", false),
  s("Networking Foundations - Semester 3",                "G","Interdisciplinary",                "1/2 Year", false),
  s("Networking Foundations - Semester 4",                "G","Interdisciplinary",                "1/2 Year", false),
  s("Networking Foundations - Semester 5",                "G","Interdisciplinary",                "1/2 Year", false),
  s("Networking Foundations - Semester 6",                "G","Interdisciplinary",                "1/2 Year", false),
  s("Nursing and Healthcare Fundamentals - Semester 1",   "G","Interdisciplinary",                "1/2 Year", false),
  s("Nursing and Healthcare Fundamentals - Semester 2",   "G","Interdisciplinary",                "1/2 Year", false),
  s("Ocean Studies - Semester 1",                         "G","Interdisciplinary",                "1/2 Year", false),
  s("Ocean Studies - Semester 2",                         "G","Interdisciplinary",                "1/2 Year", false),
  s("Office 365 Applications - Semester 5",               "G","Interdisciplinary",                "1/2 Year", false),
  s("Operations Management Foundations - Semester 1",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Operations Management Foundations - Semester 2",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Organic Gardening and Food Systems - Semester 1",    "G","Science - Biology / Life Sciences","1/2 Year", false),
  s("Organic Gardening and Food Systems - Semester 2",    "G","Science - Biology / Life Sciences","1/2 Year", false),
  s("Pandemic Reflections: COVID-19 and Society",         "G","History / Social Science",         "1/2 Year", false),
  s("Paralegal Studies - Semester 1",                     "G","Interdisciplinary",                "1/2 Year", false),
  s("Paralegal Studies - Semester 2",                     "G","Interdisciplinary",                "1/2 Year", false),
  s("PCs and Laptop Fundamentals - Semester 1",           "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("PCs and Laptop Fundamentals - Semester 2",           "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Personal Finance and Financial Literacy - Semester 1","G","Interdisciplinary",               "1/2 Year", false),
  s("Personal Finance and Financial Literacy - Semester 2","G","Interdisciplinary",               "1/2 Year", false),
  s("Personal Finance Foundations - Semester 1",          "G","Interdisciplinary",                "1/2 Year", false),
  s("Personal Finance Foundations - Semester 2",          "G","Interdisciplinary",                "1/2 Year", false),
  s("Philosophy: God, AI, & Us",                          "G","Interdisciplinary",                "1/2 Year", false),
  s("Podcasting and Digital Audio Production - Semester 1","G","Interdisciplinary",               "1/2 Year", false),
  s("Podcasting and Digital Audio Production - Semester 2","G","Interdisciplinary",               "1/2 Year", false),
  s("Principles of Accounting - Semester 1",              "G","Interdisciplinary",                "1/2 Year", false),
  s("Principles of Accounting - Semester 2",              "G","Interdisciplinary",                "1/2 Year", false),
  s("Product Management and Innovation - Semester 1",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Product Management and Innovation - Semester 2",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Professional Networking and Career Development - Semester 1","G","History / Social Science", "1/2 Year", false),
  s("Professional Networking and Career Development - Semester 2","G","History / Social Science", "1/2 Year", false),
  s("Project Management Principles and Practices - Semester 1","G","Interdisciplinary",           "1/2 Year", false),
  s("Project Management Principles and Practices - Semester 2","G","Interdisciplinary",           "1/2 Year", false),
  s("Protests and Social Movements in the 21st Century",  "G","History / Social Science",         "1/2 Year", false),
  s("Public Relations and Media Strategy - Semester 1",   "G","Interdisciplinary",                "1/2 Year", false),
  s("Public Relations and Media Strategy - Semester 2",   "G","Interdisciplinary",                "1/2 Year", false),
  s("Python for Data Science",                            "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Python for Data Science - Semester 1",               "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Python for Data Science - Semester 2",               "G","Interdisciplinary",                "1/2 Year", false),
  s("Python Foundations - Semester 1",                    "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Python Foundations - Semester 2",                    "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Python Foundations - Semester 3",                    "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("R Programming and Data Analysis",                    "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Raising Goats Foundations - Semester 1",             "G","Interdisciplinary",                "1/2 Year", false),
  s("Raising Goats Foundations - Semester 2",             "G","Interdisciplinary",                "1/2 Year", false),
  s("Research Methods in Psychology - Semester 1",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Research Methods in Psychology - Semester 2",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Resume Writing and Career Skills - Semester 1",      "G","Interdisciplinary",                "1/2 Year", false),
  s("Resume Writing and Career Skills - Semester 2",      "G","Interdisciplinary",                "1/2 Year", false),
  s("Running a Restaurant and Hospitality Management - Semester 1","G","Interdisciplinary",       "1/2 Year", false),
  s("Running a Restaurant and Hospitality Management - Semester 2","G","Interdisciplinary",       "1/2 Year", false),
  s("Screenwriting and Storytelling - Semester 1",        "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Screenwriting and Storytelling - Semester 2",        "G","Visual & Performing Arts",         "1/2 Year", false),
  s("Scrum Fundamentals - Semester 1",                    "G","Interdisciplinary",                "1/2 Year", false),
  s("Scrum Fundamentals - Semester 2",                    "G","Interdisciplinary",                "1/2 Year", false),
  s("Security Awareness Program Development - Semester 1","G","Interdisciplinary",                "1/2 Year", false),
  s("Security Awareness Program Development - Semester 2","G","Interdisciplinary",                "1/2 Year", false),
  s("September 11th and Its Aftermath",                   "G","History / Social Science",         "1/2 Year", false),
  s("Small Business and Entrepreneurship - Semester 1",   "G","Mathematics",                      "1/2 Year", false),
  s("Small Business and Entrepreneurship - Semester 2",   "G","Mathematics",                      "1/2 Year", false),
  s("Smart Cities and Urban Innovation - Semester 1",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Smart Cities and Urban Innovation - Semester 2",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Social Media Marketing and Strategy - Semester 1",   "G","Interdisciplinary",                "1/2 Year", false),
  s("Social Media Marketing and Strategy - Semester 3",   "G","Interdisciplinary",                "1/2 Year", false),
  s("Social Media Marketing and Strategy - Semester 4",   "G","Interdisciplinary",                "1/2 Year", false),
  s("Stanford Medicine: Mind Magic",                      "G","Interdisciplinary",                "1/2 Year", false),
  s("Starting a Business Foundations - Semester 1",       "G","Interdisciplinary",                "1/2 Year", false),
  s("Starting a Business Foundations - Semester 2",       "G","Interdisciplinary",                "1/2 Year", false),
  s("Supply Chain Management and Logistics - Semester 1", "G","Interdisciplinary",                "1/2 Year", false),
  s("Supply Chain Management and Logistics - Semester 2", "G","Interdisciplinary",                "1/2 Year", false),
  s("Sustainable Fashion and Design - Semester 1",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Sustainable Fashion and Design - Semester 2",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Sustainable Landscaping and Design - Semester 1",    "G","Science - Biology / Life Sciences","1/2 Year", false),
  s("Sustainable Landscaping and Design - Semester 2",    "G","Science - Biology / Life Sciences","1/2 Year", false),
  s("Sustainable Travel and Tourism - Semester 1",        "G","Interdisciplinary",                "1/2 Year", false),
  s("Sustainable Travel and Tourism - Semester 2",        "G","Interdisciplinary",                "1/2 Year", false),
  s("SwiftUI Development",                                "G","Interdisciplinary",                "1/2 Year", false),
  s("Teaching STEM in the 21st Century - Semester 1",     "G","Interdisciplinary",                "1/2 Year", false),
  s("Teaching STEM in the 21st Century - Semester 2",     "G","Interdisciplinary",                "1/2 Year", false),
  s("The American Dream and Social Change: Migration, Identity, and Protest","G","History / Social Science","1/2 Year",false),
  s("The COVID-19 Pandemic",                              "G","Interdisciplinary",                "1/2 Year", false),
  s("The Holocaust and Human Rights: Memory and Responsibility","G","History / Social Science",   "1/2 Year", false),
  s("The Metaverse and Virtual Worlds - Semester 1",      "G","Interdisciplinary",                "1/2 Year", false),
  s("The Metaverse and Virtual Worlds - Semester 2",      "G","Interdisciplinary",                "1/2 Year", false),
  s("Training and Development Fundamentals - Semester 1", "G","Interdisciplinary",                "1/2 Year", false),
  s("Training and Development Fundamentals - Semester 2", "G","Interdisciplinary",                "1/2 Year", false),
  s("User Experience (UX) Design - Semester 1",           "G","Interdisciplinary",                "1/2 Year", false),
  s("User Experience (UX) Design - Semester 2",           "G","Interdisciplinary",                "1/2 Year", false),
  s("Video Game Design Foundations - Semester 1",         "G","Interdisciplinary",                "1/2 Year", false),
  s("Video Game Design Foundations - Semester 2",         "G","Interdisciplinary",                "1/2 Year", false),
  s("Web Application Development",                        "G","Interdisciplinary",                "1 Year",   false),
  s("Web Development and Coding Practices - Semester 1",  "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Web Development and Coding Practices - Semester 2",  "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Web Development and Coding Practices - Semester 3",  "G","Mathematics - Computer Science",   "1/2 Year", false),
  s("Web Development with PHP, MySQL, and JavaScript",    "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Website Building Fundamentals",                      "G","Interdisciplinary",                "1/2 Year", false),
  s("Website Design and Development for the Digital Age", "G","Mathematics - Computer Science",   "1 Year",   false),
  s("Witness to History: War, Memory, and Society",       "G","History / Social Science",         "1/2 Year", false),
  s("Women in History and Society",                       "G","History / Social Science",         "1/2 Year", false),
  s("Workplace Foundations and Productivity - Semester 3","G","Interdisciplinary",                "1/2 Year", false),
  s("Workplace Health and Safety - Semester 1",           "G","Interdisciplinary",                "1/2 Year", false),
  s("Workplace Health and Safety - Semester 2",           "G","Interdisciplinary",                "1/2 Year", false),
  s("World History and Global Perspectives - Semester 1", "G","History / Social Science",         "1/2 Year", false),
  s("World History and Global Perspectives - Semester 2", "G","History / Social Science",         "1/2 Year", false),
  s("Zero Waste Cooking and Sustainability - Semester 1", "G","Interdisciplinary",                "1/2 Year", false),
]

export function getCourseBySlug(slug: string): Course | undefined {
  return COURSES.find((c) => c.slug === slug)
}

export function getCoursesBySection(section: UcSection): Course[] {
  return COURSES.filter((c) => c.section === section)
}
